// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.UploadBlob(System.Collections.Generic.List{Microsoft.AspNetCore.Http.IFormFile})~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.ListContainers(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.ListBlobs(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.DownloadBlob(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.Progress(System.Boolean)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.DeleteBlob(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.ExistsBlob(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Controllers.HomeController.Progress(System.Boolean,System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Need to catch all exception.", Scope = "member", Target = "~M:AzureBlobExplorer.Helper.ContainerHelper.ExistsBlobAsync(System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
